# Generated by Django 3.0 on 2020-01-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_assesments'),
    ]

    operations = [
        migrations.CreateModel(
            name='assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('a_subject', models.CharField(max_length=100)),
                ('a_no', models.IntegerField()),
                ('t_total', models.IntegerField()),
                ('t_mark', models.IntegerField()),
                ('b_batch', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'assesments',
            },
        ),
        migrations.DeleteModel(
            name='assesments',
        ),
    ]
