# Generated by Django 3.0 on 2020-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200107_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_addno', models.IntegerField()),
                ('a_date', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('a_h1', models.CharField(max_length=10)),
                ('a_h2', models.CharField(max_length=10)),
                ('a_h3', models.CharField(max_length=10)),
                ('a_h4', models.CharField(max_length=10)),
                ('b_batch', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'attendance_table',
            },
        ),
    ]
