# Generated by Django 3.0 on 2020-01-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='facultyleave',
        ),
    ]
