# Generated by Django 3.0 on 2020-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_facultyleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField()),
                ('f_name', models.CharField(max_length=50)),
                ('l_fromdate', models.CharField(max_length=50)),
                ('l_todate', models.CharField(max_length=50)),
                ('l_reason', models.CharField(max_length=500)),
                ('l_status', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'faculty_leave_details',
            },
        ),
        migrations.CreateModel(
            name='studentleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=50)),
                ('l_fromdate', models.CharField(max_length=50)),
                ('l_todate', models.CharField(max_length=50)),
                ('l_reason', models.CharField(max_length=500)),
                ('l_status', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'student_leave_details',
            },
        ),
    ]
